version: '3'

services:
  zen:
    build:
      context: .
      args:
        NODE_VERSION: 20.18.0 # set via --build-arg, eg "docker-compose build --build-arg NODE_VERSION=16.20.2"
    image: zen:${NODE_VERSION}
    environment:
      NODE_OPTIONS: "--max-old-space-size=12288"
    command: >
      sh -c "
        whoami | xargs echo "User:"
        node --version | xargs echo 'test-node-version.sh: Starting NODE_VERSION=${NODE_VERSION}, \"node --version\"='
        npm run start
        node --version | xargs echo 'test-node-version.sh: Finished NODE_VERSION=${NODE_VERSION}, \"node --version\"='
      "

    volumes:
      - './:/home/service-project'
