// @-ts-nocheck
import { add_CommonProps, Tvalues } from '../../../../../test-utils/test-data'
/*{ @common-imports-in-tests-templates }*/
import { ValueOfStrict } from '../../../../index'
import {
  date_prototype_stringNonEnumerablesInherited,
  date_prototype_stringNonEnumerablesInherited_ES2023,
  date_prototype_stringNonEnumerablesOwn,
  date_prototype_symbolNonEnumerablesInherited,
  Tdate_prototype_stringNonEnumerablesInherited,
  Tdate_prototype_stringNonEnumerablesInherited_values,
  Tdate_prototype_stringNonEnumerablesOwn,
  Tdate_prototype_stringNonEnumerablesOwn_values,
  Tdate_prototype_symbolNonEnumerablesInherited,
  Tdate_prototype_symbolNonEnumerablesInherited_values,
} from '../../../../typezen/types-info'

let inputVanilla: any // leave this as any, generated by template

describe('Singles/Objects', () => {
  const inputTitle = `Date` // just for title
  describe(inputTitle, () => {
    const getInputVanilla = () => new Date(`2024-06-08`)
    const getInputWithExtraCommonProps = () => add_CommonProps(getInputVanilla())
    let inputVanilla = getInputVanilla()
    let inputWithExtraCommonProps = getInputWithExtraCommonProps()

    const isInspectableNested = false

    type Texpected_nested_keys = typeof isInspectableNested extends false ? never : number
    const expected_nested_keys: Texpected_nested_keys[] = !isInspectableNested ? [] : []

    /*{ @common-own-inherited-enumerable-props }*/

    // prototype / base-type props

    // own nonEnumerable props
    type Texpected_stringNonEnumerablesOwn = Tdate_prototype_stringNonEnumerablesOwn
    const expected_stringNonEnumerablesOwn = [...date_prototype_stringNonEnumerablesOwn]
    type Texpected_symbolNonEnumerablesOwn = never
    const expected_symbolNonEnumerablesOwn = []

    // inherited props
    type Texpected_stringNonEnumerablesInherited = Tdate_prototype_stringNonEnumerablesInherited
    const expected_stringNonEnumerablesInherited = [...date_prototype_stringNonEnumerablesInherited, ...(([] as any).findLastIndex ? date_prototype_stringNonEnumerablesInherited_ES2023 : [])]
    type Texpected_symbolNonEnumerablesInherited = Tdate_prototype_symbolNonEnumerablesInherited
    const expected_symbolNonEnumerablesInherited = [...date_prototype_symbolNonEnumerablesInherited]

    // ### Values ###

    type Texpected_nested_items = typeof isInspectableNested extends false ? never : Tvalues
    const expected_nested_items: Texpected_nested_items[] = !isInspectableNested ? [] : []

    // prototype / base-type values

    // own nonEnumerables values
    type Texpected_stringNonEnumerablesOwn_values = Tdate_prototype_stringNonEnumerablesOwn_values
    const expected_stringNonEnumerablesOwn_values = date_prototype_stringNonEnumerablesOwn.map((value) => inputVanilla[value])
    type Texpected_symbolNonEnumerablesOwn_values = never
    const expected_symbolNonEnumerablesOwn_values = []

    // inherited values
    type Texpected_stringNonEnumerablesInherited_values = Tdate_prototype_stringNonEnumerablesInherited_values
    type Texpected_symbolNonEnumerablesInherited_values = Tdate_prototype_symbolNonEnumerablesInherited_values

    // top values

    type Texpected_stringNonEnumerablesInheritedTop_values = ValueOfStrict<Object, Exclude<keyof Object, keyof Date>>

    /*{ @default-expected-keys-values-iteration }*/

    describe(`all-typings-tests for override`, () => {
      // default overrides here
      type Texpected_iteration_keys = null
      const expected_iteration_keys: Texpected_iteration_keys[] = [null]
      type Texpected_iteration_items = typeof inputVanilla
      const expected_iteration_items = [inputVanilla]

      type Texpected_callback_keys = null
      const expected_callback_keys: Texpected_callback_keys[] = [null]
      type Texpected_callback_items = ReturnType<typeof inputVanilla.valueOf> // string / number / boolean
      const expected_callback_items = [inputVanilla.valueOf()]

      /*{ @all-typings-tests-vanilla }*/
      /*{ @all-typings-tests-WECP }*/
      /*{ @all-typings-tests-options-wrong }*/
    })
  })
})
