// @-ts-nocheck
/*{ @common-imports-in-tests-templates }*/
import { a_Promise, a_Promise_withCommonProps, add_CommonProps, PROMISE_RESOLVED_VALUE, Tvalues } from '../../../../../test-utils/test-data'
import { ValueOfStrict } from '../../../../index'
import {
  promise_prototype_stringNonEnumerablesInherited,
  promise_prototype_stringNonEnumerablesInherited_ES2023,
  promise_prototype_stringNonEnumerablesOwn,
  promise_prototype_symbolNonEnumerablesInherited,
  Tpromise_prototype_stringNonEnumerablesInherited,
  Tpromise_prototype_stringNonEnumerablesInherited_values,
  Tpromise_prototype_stringNonEnumerablesOwn,
  Tpromise_prototype_stringNonEnumerablesOwn_values,
  Tpromise_prototype_symbolNonEnumerablesInherited,
  Tpromise_prototype_symbolNonEnumerablesInherited_values,
} from '../../../../typezen/types-info'

let inputVanilla: any // leave this as any, generated by template

describe('Singles/Objects', () => {
  const inputTitle = `Promise` // just for title
  describe(inputTitle, () => {
    let inputVanilla = a_Promise
    let inputWithExtraCommonProps = a_Promise_withCommonProps
    const getInputVanilla = () => inputVanilla
    const getInputWithExtraCommonProps = () => inputWithExtraCommonProps

    const isInspectableNested = false

    // ### Keys / Props ###

    type Texpected_nested_keys = typeof isInspectableNested extends false ? never : number
    const expected_nested_keys: Texpected_nested_keys[] = !isInspectableNested ? [] : []

    /*{ @common-own-inherited-enumerable-props }*/

    // prototype / base-type props

    // own nonEnumerable props
    type Texpected_stringNonEnumerablesOwn = Tpromise_prototype_stringNonEnumerablesOwn
    const expected_stringNonEnumerablesOwn = [...promise_prototype_stringNonEnumerablesOwn]
    type Texpected_symbolNonEnumerablesOwn = never
    const expected_symbolNonEnumerablesOwn = []

    // inherited props
    type Texpected_stringNonEnumerablesInherited = Tpromise_prototype_stringNonEnumerablesInherited
    const expected_stringNonEnumerablesInherited = [...promise_prototype_stringNonEnumerablesInherited, ...(([] as any).findLastIndex ? promise_prototype_stringNonEnumerablesInherited_ES2023 : [])]
    type Texpected_symbolNonEnumerablesInherited = Tpromise_prototype_symbolNonEnumerablesInherited
    const expected_symbolNonEnumerablesInherited = [...promise_prototype_symbolNonEnumerablesInherited]

    // ### Values ###

    type Texpected_nested_items = typeof isInspectableNested extends false ? never : Tvalues
    const expected_nested_items: Texpected_nested_items[] = !isInspectableNested ? [] : []

    // prototype / base-type values

    // own nonEnumerables values
    type Texpected_stringNonEnumerablesOwn_values = Tpromise_prototype_stringNonEnumerablesOwn_values<typeof inputVanilla>
    const expected_stringNonEnumerablesOwn_values = expected_stringNonEnumerablesOwn.map((value) => inputVanilla[value])
    type Texpected_symbolNonEnumerablesOwn_values = never
    const expected_symbolNonEnumerablesOwn_values = []

    // inherited values
    type Texpected_stringNonEnumerablesInherited_values = Tpromise_prototype_stringNonEnumerablesInherited_values<typeof inputVanilla>
    type Texpected_symbolNonEnumerablesInherited_values = Tpromise_prototype_symbolNonEnumerablesInherited_values<typeof inputVanilla>

    // top values
    type Texpected_stringNonEnumerablesInheritedTop_values = ValueOfStrict<Object, Exclude<keyof Object, keyof Promise<any>>>

    /*{ @default-expected-keys-values-iteration }*/

    describe(`all-typings-tests for override`, () => {
      // default overrides here
      type Texpected_iteration_keys = null
      const expected_iteration_keys: Texpected_iteration_keys[] = [null]
      type Texpected_iteration_items = typeof inputVanilla
      const expected_iteration_items = [inputVanilla]

      type Texpected_callback_keys = null
      const expected_callback_keys: Texpected_callback_keys[] = [null]

      type Texpected_callback_items = Awaited<typeof inputVanilla> // | 'SHOULD FAIL'
      const expected_callback_items = [PROMISE_RESOLVED_VALUE + 'SHOULD FAIL'] //  @todo(333): this should fail, but not used ;-)

      /*{ @all-typings-tests-vanilla }*/
      /*{ @all-typings-tests-WECP }*/
      /*{ @all-typings-tests-options-wrong }*/
    })
  })
})
