export { LogZen } from './LogZen'
export { getTinyLog } from './utils/tiny-log'
export {
  BuiltInOutputsOptions,
  ELogLevel,
  Header,
  LogZenInspectOptions,
  IOutputLogInfo,
  LogLevelDescriptions,
  Options,
  OptionsAtConstructor,
  OptionsInternal,
  Output,
  TBuiltInOutputNames,
  TLog1MethodArgsToReturnLastArg,
  TLogPathOptions,
  TOutputFn,
  TPathReplacements,
  Tlog1Method,
  TlogMethod,
  TraceOptions,
  PrintOptions,
  TwillLogMethod,
  allLogMethodNames,
  logLevelEnumToNumberVal,
  logLevelEnumToStringKey,
  logLevelMethodNames,
} from './types'
